services: 
   mongo: #Servidor de base de datos
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    networks:
      - app-network
    volumes:
      - mongo_data_2:/data/db # Volumen gestionado por docker =! carpeta en local mapeada

volumes:
  mongo_data_2: # Nombre exacto del volumen creado por el compose grande

networks:
  app-network:
    external: true
    