services: 
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    networks:
      - app-network
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_MONGODB_SERVER: mongo

networks:
  app-network:
    external: true
    