
services:
  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - app-network


networks:
  app-network:
    external: true


