version: '3.8'

services:
  # Servicio para cargar archivos JSON a MongoDB
  json_loader:
    build: .
    container_name: json-loader
    volumes:
      - ./jsons:/app/jsons
    environment:
      - MONGODB_URI=mongodb://admin:admin123@mongo:27017/
      - MONGODB_DB=trafico_rm
      - MONGODB_COLECCION_ALERTAS=alertas
      - MONGODB_COLECCION_ATASCOS=atascos
    depends_on:
      - mongo

  # Base de datos MongoDB
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db

  # Interfaz web para MongoDB
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  mongo_data: