version: '3.8'

services:
  # Servicio para cargar archivos JSON a MongoDB
  json_loader:
    build: .
    container_name: json-loader
    volumes:
      - ./jsons:/app/jsons
    environment:
      - MONGODB_URI=mongodb://admin:admin123@mongo:27017/
      - MONGODB_DB=trafico_rm
      - MONGODB_COLECCION_ALERTAS=alertas
      - MONGODB_COLECCION_ATASCOS=atascos
    networks:
      - app-network

networks:
  app-network:
    external: true  # Usará una red existente llamada 'app-network'