
services:

  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    networks:
      - app-network

networks:
  app-network:
    external: true


