services:
  generador_trafico:
    build: .
    container_name: generador_trafico_zipf
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./:/app 

networks:
  app-network:
    external: true