version: '3.8'

services:
  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_volume_data:/data

  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db

  python_app:
    build: ./app
    container_name: redis_python_app
    restart: on-failure
    depends_on:
      - redis

volumes:
  redis_volume_data:
  redis_insight_volume_data:
